### ISSUE TITLE
Issue logging in

### ISSUE THREAD

**Issue by ModernIcarus** [Provinite/toyhouse-downloader#4]
having an issue when attempting to log in
getting this error
 [ThD][03:25:43] debug : Navigated to https://toyhou.se/~account/login
 [ThD][03:25:49] error : Fatal error during downloading process
 [ThD][03:25:49] error : undefined
 [ThD][03:25:49] error : Error: Evaluation failed: TypeError: Cannot read properties of null (reading 'click')
    at clickLogin (pptr://__puppeteer_evaluation_script__:3:22)
    at ExecutionContext._ExecutionContext_evaluate (C:\snapshot\toyhouse-downloader\node_modules\puppeteer-core\lib\cjs\puppeteer\common\ExecutionContext.js:229:15)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async ExecutionContext.evaluate (C:\snapshot\toyhouse-downloader\node_modules\puppeteer-core\lib\cjs\puppeteer\common\ExecutionContext.js:107:16)
    at async loginToToyhouse (C:\snapshot\toyhouse-downloader\build\toyhouse.puppeteer.js:30:9)
    at async main (C:\snapshot\toyhouse-downloader\build\app.js:40:9)
 [ThD][03:25:49] info  : Shutting down

**Comment by Provinite** [comment]
Hey @ModernIcarus  thanks for reporting this! Are you running the latest version?

**Comment by Provinite** [comment]
Oh, also, what platform? (windows, mac, linux)

**Comment by ModernIcarus** [comment]
> Hey @ModernIcarus thanks for reporting this! Are you running the latest version?

yeah, double checked it was the most recent version, also I'm using windows!
